  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "regression_section"
   },
   "source": [
    "## 📈 Step 4: Regression Models"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "regression_functions"
   },
   "outputs": [],
   "source": [
    "def compute_metrics(y_true, y_pred, n_features):\n",
    "    \"\"\"Compute regression metrics.\"\"\"\n",
    "    n = len(y_true)\n",
    "    mse = mean_squared_error(y_true, y_pred)\n",
    "    rmse = np.sqrt(mse)\n",
    "    mae = mean_absolute_error(y_true, y_pred)\n",
    "    r2 = r2_score(y_true, y_pred)\n",
    "    \n",
    "    # Calculate adjusted R-squared\n",
    "    if n - n_features - 1 > 0:\n",
    "        adj_r2 = 1 - (1 - r2) * (n - 1) / (n - n_features - 1)\n",
    "    else:\n",
    "        adj_r2 = np.nan\n",
    "    \n",
    "    return {\n",
    "        'r2': r2,\n",
    "        'adj_r2': adj_r2,\n",
    "        'rmse': rmse,\n",
    "        'mae': mae\n",
    "    }\n",
    "\n",
    "def train_models(X_train, X_test, y_train, y_test):\n",
    "    \"\"\"Train and evaluate multiple regression models.\"\"\"\n",
    "    n_features = X_train.shape[1]\n",
    "    results = []\n",
    "    models = {}\n",
    "    \n",
    "    # Define models to train\n",
    "    model_configs = [\n",
    "        ('LinearRegression', LinearRegression()),\n",
    "        ('DecisionTree', DecisionTreeRegressor(random_state=RANDOM_STATE)),\n",
    "        ('RandomForest', RandomForestRegressor(n_estimators=200, random_state=RANDOM_STATE))\n",
    "    ]\n",
    "    \n",
    "    for name, model in model_configs:\n",
    "        print(f\"\\nTraining {name}...\")\n",
    "        start_time = time()\n",
    "        \n",
    "        # Train model\n",
    "        model.fit(X_train, y_train)\n",
    "        \n",
    "        # Make predictions\n",
    "        y_pred = model.predict(X_test)\n",
    "        \n",
    "        # Compute metrics\n",
    "        metrics = compute_metrics(y_test, y_pred, n_features)\n",
    "        metrics['training_time'] = time() - start_time\n",
    "        \n",
    "        # Store results\n",
    "        results.append({\n",
    "            'model': name,\n",
    "            **metrics\n",
    "        })\n",
    "        \n",
    "        # Store model\n",
    "        models[name] = model\n",
    "        \n",
    "        print(f\"  - R²: {metrics['r2']:.4f}\")\n",
    "        print(f\"  - Adj. R²: {metrics['adj_r2']:.4f}\")\n",
    "        print(f\"  - RMSE: {metrics['rmse']:.4f}\")\n",
    "        print(f\"  - MAE: {metrics['mae']:.4f}\")\n",
    "        print(f\"  - Training time: {metrics['training_time']:.2f}s\")\n",
    "    \n",
    "    return pd.DataFrame(results), models\n",
    "\n",
    "print(\"✅ Regression functions defined successfully!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "run_regression"
   },
   "outputs": [],
   "source": [
    "# Run regression models\n",
    "print(\"📈 Starting regression model training...\")\n",
    "\n",
    "print(f\"Training set: {X_train.shape[0]} samples, {X_train.shape[1]} features\")\n",
    "print(f\"Test set: {X_test.shape[0]} samples\")\n",
    "\n",
    "# Train and evaluate models\n",
    "results_df, models = train_models(X_train, X_test, y_train, y_test)\n",
    "\n",
    "# Save results\n",
    "results_df.to_csv(\"output/models/regression_results.csv\", index=False)\n",
    "\n",
    "# Find and save best model\n",
    "best_model_row = results_df.loc[results_df['adj_r2'].idxmax()]\n",
    "best_model_name = best_model_row['model']\n",
    "best_model = models[best_model_name]\n",
    "\n",
    "# Save the best model\n",
    "joblib.dump(best_model, \"output/models/best_regressor.joblib\")\n",
    "\n",
    "# Save all models\n",
    "for name, model in models.items():\n",
    "    joblib.dump(model, f\"output/models/{name.lower()}.joblib\")\n",
    "\n",
    "print(f\"\\n✅ Training completed!\")\n",
    "print(f\"\\nBest model: {best_model_name}\")\n",
    "print(f\"- Adj. R²: {best_model_row['adj_r2']:.4f}\")\n",
    "print(f\"- RMSE: {best_model_row['rmse']:.4f}\")\n",
    "\n",
    "# Display results table\n",
    "print(\"\\n📊 Model Performance Summary:\")\n",
    "display(results_df[['model', 'adj_r2', 'rmse', 'mae', 'training_time']])\n",
    "\n",
    "# Create visualization\n",
    "fig = px.bar(\n",
    "    results_df, \n",
    "    x='model', \n",
    "    y='adj_r2',\n",
    "    title='Model Performance Comparison (Adjusted R²)',\n",
    "    labels={'adj_r2': 'Adjusted R²', 'model': 'Model'}\n",
    ")\n",
    "fig.show()\n",
    "\n",
    "# Store best model for predictions\n",
    "globals()['best_model'] = best_model\n",
    "globals()['sbert_model'] = model  # The SBERT model from text processing"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "clustering_section"
   },
   "source": [
    "## 🎯 Step 5: Clustering Analysis"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "clustering_functions"
   },
   "outputs": [],
   "source": [
    "def find_optimal_k(X_scaled, k_range=range(2, 11)):\n",
    "    \"\"\"Find the optimal number of clusters using silhouette score.\"\"\"\n",
    "    print(\"Finding optimal number of clusters...\")\n",
    "    \n",
    "    silhouette_scores = []\n",
    "    for k in k_range:\n",
    "        k = int(k)\n",
    "        if k >= len(X_scaled):\n",
    "            print(f\"Skipping k={k} (more clusters than samples)\")\n",
    "            continue\n",
    "            \n",
    "        print(f\"  Testing k={k}...\")\n",
    "        \n",
    "        # KMeans\n",
    "        kmeans = KMeans(n_clusters=k, random_state=RANDOM_STATE, n_init=10)\n",
    "        kmeans_labels = kmeans.fit_predict(X_scaled)\n",
    "        kmeans_score = silhouette_score(X_scaled, kmeans_labels)\n",
    "        \n",
    "        # Agglomerative Clustering\n",
    "        agg = AgglomerativeClustering(n_clusters=k)\n",
    "        agg_labels = agg.fit_predict(X_scaled)\n",
    "        agg_score = silhouette_score(X_scaled, agg_labels)\n",
    "        \n",
    "        silhouette_scores.append({\n",
    "            'k': k,\n",
    "            'kmeans_silhouette': kmeans_score,\n",
    "            'agg_silhouette': agg_score\n",
    "        })\n",
    "    \n",
    "    return pd.DataFrame(silhouette_scores)\n",
    "\n",
    "def train_best_clusterer(X_scaled, k):\n",
    "    \"\"\"Train the best clustering model for the given k.\"\"\"\n",
    "    k = max(2, min(int(round(k)), len(X_scaled) - 1))\n",
    "    \n",
    "    print(f\"Training with k={k} clusters...\")\n",
    "    \n",
    "    # Try both KMeans and Agglomerative clustering\n",
    "    kmeans = KMeans(n_clusters=k, random_state=RANDOM_STATE, n_init=10)\n",
    "    kmeans_labels = kmeans.fit_predict(X_scaled)\n",
    "    kmeans_score = silhouette_score(X_scaled, kmeans_labels)\n",
    "    print(f\"  KMeans silhouette score: {kmeans_score:.4f}\")\n",
    "    \n",
    "    agg = AgglomerativeClustering(n_clusters=k)\n",
    "    agg_labels = agg.fit_predict(X_scaled)\n",
    "    agg_score = silhouette_score(X_scaled, agg_labels)\n",
    "    print(f\"  Agglomerative silhouette score: {agg_score:.4f}\")\n",
    "    \n",
    "    # Return the better performing model\n",
    "    if kmeans_score >= agg_score:\n",
    "        print(\"  Selected KMeans as the better model\")\n",
    "        return kmeans, kmeans_labels, 'kmeans'\n",
    "    else:\n",
    "        print(\"  Selected Agglomerative as the better model\")\n",
    "        return agg, agg_labels, 'agglomerative'\n",
    "\n",
    "print(\"✅ Clustering functions defined successfully!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "run_clustering"
   },
   "outputs": [],
   "source": [
    "# Run clustering analysis\n",
    "print(\"🎯 Starting clustering analysis...\")\n",
    "\n",
    "# Load and prepare data\n",
    "X_fused = np.load('output/features/X_fused.npy')\n",
    "scaler = StandardScaler()\n",
    "X_scaled = scaler.fit_transform(X_fused)\n",
    "\n",
    "# Find optimal number of clusters\n",
    "silhouette_df = find_optimal_k(X_scaled)\n",
    "silhouette_df.to_csv(\"output/clustering/clustering_silhouettes.csv\", index=False)\n",
    "\n",
    "# Get best k\n",
    "best_row = silhouette_df.loc[silhouette_df[['kmeans_silhouette', 'agg_silhouette']].max(axis=1).idxmax()]\n",
    "best_k = int(round(best_row['k']))\n",
    "\n",
    "# Save best k\n",
    "with open(\"output/clustering/best_k.txt\", 'w') as f:\n",
    "    f.write(str(best_k))\n",
    "\n",
    "print(f\"\\n🎯 Training best clustering model with k={best_k}...\")\n",
    "clusterer, labels, method_name = train_best_clusterer(X_scaled, best_k)\n",
    "\n",
    "# Save the clusterer\n",
    "joblib.dump(clusterer, \"output/clustering/best_clusterer.joblib\")\n",
    "\n",
    "# Save cluster assignments\n",
    "np.save(\"output/clustering/cluster_assignments.npy\", labels)\n",
    "pd.DataFrame({'cluster': labels}).to_csv(\"output/clustering/cluster_assignments.csv\", index=False)\n",
    "\n",
    "# Create cluster visualization\n",
    "unique, counts = np.unique(labels, return_counts=True)\n",
    "\n",
    "plt.figure(figsize=(10, 6))\n",
    "plt.bar(unique, counts)\n",
    "plt.title(f'Cluster Sizes ({method_name.title()})')\n",
    "plt.xlabel('Cluster')\n",
    "plt.ylabel('Number of Samples')\n",
    "plt.grid(True, alpha=0.3)\n",
    "plt.tight_layout()\n",
    "plt.savefig('output/clustering/cluster_sizes.png')\n",
    "plt.show()\n",
    "\n",
    "# Display cluster statistics\n",
    "cluster_stats = pd.DataFrame({\n",
    "    'Cluster': unique,\n",
    "    'Count': counts,\n",
    "    'Percentage': (counts / len(labels) * 100).round(2)\n",
    "})\n",
    "\n",
    "print(\"\\n📊 Cluster Statistics:\")\n",
    "display(cluster_stats)\n",
    "\n",
    "# Show silhouette scores\n",
    "print(\"\\n📈 Silhouette Scores by K:\")\n",
    "display(silhouette_df)\n",
    "\n",
    "# Create silhouette score plot\n",
    "fig = px.line(\n",
    "    silhouette_df, \n",
    "    x='k', \n",
    "    y=['kmeans_silhouette', 'agg_silhouette'],\n",
    "    title='Silhouette Scores by Number of Clusters',\n",
    "    labels={'value': 'Silhouette Score', 'k': 'Number of Clusters'}\n",
    ")\n",
    "fig.show()\n",
    "\n",
    "print(f\"\\n✅ Clustering analysis complete!\")\n",
    "print(f\"- Optimal k: {best_k}\")\n",
    "print(f\"- Best method: {method_name}\")\n",
    "\n",
    "# Store for later use\n",
    "globals()['cluster_labels'] = labels\n",
    "globals()['best_clusterer'] = clusterer"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "interactive_section"
   },
   "source": [
    "## 🎮 Step 6: Interactive Prediction and Analysis"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "interactive_functions"
   },
   "outputs": [],
   "source": [
    "# Define interactive prediction functions\n",
    "def preprocess_text_for_prediction(text, preprocessor, sbert_model):\n",
    "    \"\"\"Preprocess text and generate embeddings for prediction.\"\"\"\n",
    "    # Clean the text\n",
    "    cleaned_text = preprocessor.clean_text(text)\n",
    "    \n",
    "    # Generate embeddings\n",
    "    embedding = sbert_model.encode([cleaned_text], normalize_embeddings=True)[0]\n",
    "    \n",
    "    return embedding, cleaned_text\n",
    "\n",
    "def make_prediction_from_features(model, numeric_features, categorical_features, text_embedding=None):\n",
    "    \"\"\"Make a prediction from given features.\"\"\"\n",
    "    # Create feature vector (simplified version)\n",
    "    # In a real implementation, you'd need to handle the exact preprocessing pipeline\n",
    "    \n",
    "    # For demonstration, we'll create a simplified feature vector\n",
    "    feature_vector = np.array(numeric_features)\n",
    "    \n",
    "    # Add text embedding if provided\n",
    "    if text_embedding is not None:\n",
    "        feature_vector = np.concatenate([feature_vector, text_embedding])\n",
    "    \n",
    "    # Ensure the feature vector has the right shape\n",
    "    if len(feature_vector) != X_train.shape[1]:\n",
    "        # Pad or truncate to match training data dimensions\n",
    "        if len(feature_vector) < X_train.shape[1]:\n",
    "            feature_vector = np.pad(feature_vector, (0, X_train.shape[1] - len(feature_vector)))\n",
    "        else:\n",
    "            feature_vector = feature_vector[:X_train.shape[1]]\n",
    "    \n",
    "    # Make prediction\n",
    "    prediction = model.predict(feature_vector.reshape(1, -1))[0]\n",
    "    \n",
    "    return prediction\n",
    "\n",
    "def analyze_text_features(text, preprocessor, show_steps=True):\n",
    "    \"\"\"Analyze text and show preprocessing steps.\"\"\"\n",
    "    if show_steps:\n",
    "        print(\"\\n🔍 Text Analysis Steps:\")\n",
    "        print(f\"\\n1. Original text:\")\n",
    "        print(f\"   '{text}'\")\n",
    "        \n",
    "        # Show cleaning process\n",
    "        cleaned = preprocessor.clean_text(text, verbose=False)\n",
    "        print(f\"\\n2. After preprocessing:\")\n",
    "        print(f\"   '{cleaned}'\")\n",
    "        \n",
    "        # Basic text statistics\n",
    "        words = text.split()\n",
    "        print(f\"\\n3. Text statistics:\")\n",
    "        print(f\"   - Characters: {len(text)}\")\n",
    "        print(f\"   - Words: {len(words)}\")\n",
    "        print(f\"   - Sentences: {len([s for s in text.split('.') if s.strip()])}\")\n",
    "        \n",
    "        return cleaned\n",
    "    else:\n",
    "        return preprocessor.clean_text(text)\n",
    "\n",
    "print(\"✅ Interactive functions defined successfully!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "prediction_examples"
   },
   "source": [
    "### 🎯 Make Predictions\n",
    "\n",
    "Now you can make predictions using the trained models. Here are some examples:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "text_prediction_example"
   },
   "outputs": [],
   "source": [
    "# Example 1: Text-based prediction\n",
    "print(\"📝 Example 1: Text-based Prediction\")\n",
    "print(\"=\" * 50)\n",
    "\n",
    "# Sample student profile text\n",
    "sample_text = \"This student shows excellent performance in mathematics and science. \\\n",
    "They are highly motivated and participate actively in class discussions. \\\n",
    "However, they sometimes struggle with time management during exams.\"\n",
    "\n",
    "print(f\"Student profile: {sample_text}\")\n",
    "\n",
    "# Analyze the text\n",
    "cleaned_text = analyze_text_features(sample_text, preprocessor, show_steps=True)\n",
    "\n",
    "# Generate embeddings\n",
    "text_embedding = sbert_model.encode([cleaned_text], normalize_embeddings=True)[0]\n",
    "\n",
    "print(f\"\\n4. Generated embedding:\")\n",
    "print(f\"   - Dimensions: {len(text_embedding)}\")\n",
    "print(f\"   - Sample values: {text_embedding[:5]}\")\n",
    "print(f\"   - Embedding norm: {np.linalg.norm(text_embedding):.4f}\")\n",
    "\n",
    "# For a simplified prediction, we'll use just the text embedding\n",
    "# In practice, you'd need to combine this with other features properly\n",
    "try:\n",
    "    # Create a feature vector that matches the training data\n",
    "    # This is a simplified approach - in practice you'd need proper feature engineering\n",
    "    dummy_features = np.mean(X_train[:100], axis=0)  # Use mean of first 100 samples as baseline\n",
    "    \n",
    "    # Replace the embedding portion with our text embedding\n",
    "    if len(dummy_features) >= len(text_embedding):\n",
    "        # Assume embeddings are at the end\n",
    "        dummy_features[-len(text_embedding):] = text_embedding\n",
    "    \n",
    "    prediction = best_model.predict(dummy_features.reshape(1, -1))[0]\n",
    "    print(f\"\\n🎯 Predicted Final Score: {prediction:.2f}\")\n",
    "    \n",
    "except Exception as e:\n",
    "    print(f\"\\n⚠️ Prediction error: {e}\")\n",
    "    print(\"This is expected in the simplified example. In practice, you'd need proper feature preprocessing.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "interactive_input"
   },
   "outputs": [],
   "source": [
    "# Example 2: Interactive text analysis\n",
    "print(\"\\n🎮 Interactive Text Analysis\")\n",
    "print(\"=\" * 50)\n",
    "\n",
    "# You can modify this text to test different student profiles\n",
    "custom_text = input(\"Enter a student profile description (or press Enter for default): \").strip()\n",
    "\n",
    "if not custom_text:\n",
    "    custom_text = \"Student demonstrates strong analytical skills and consistently completes assignments on time. \\\n",
    "    Shows particular strength in problem-solving but needs improvement in written communication.\"\n",
    "\n",
    "print(f\"\\nAnalyzing: {custom_text}\")\n",
    "\n",
    "# Analyze the custom text\n",
    "custom_cleaned = analyze_text_features(custom_text, preprocessor, show_steps=True)\n",
    "\n",
    "# Generate and display embeddings\n",
    "custom_embedding = sbert_model.encode([custom_cleaned], normalize_embeddings=True)[0]\n",
    "\n",
    "print(f\"\\n📊 Embedding Analysis:\")\n",
    "print(f\"   - Vector dimension: {len(custom_embedding)}\")\n",
    "print(f\"   - Min value: {custom_embedding.min():.4f}\")\n",
    "print(f\"   - Max value: {custom_embedding.max():.4f}\")\n",
    "print(f\"   - Mean value: {custom_embedding.mean():.4f}\")\n",
    "\n",
    "# Show top positive and negative embedding values\n",
    "sorted_indices = np.argsort(custom_embedding)\n",
    "print(f\"\\n   Top 5 positive dimensions: {sorted_indices[-5:]}\")\n",
    "print(f\"   Top 5 negative dimensions: {sorted_indices[:5]}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "comparison_analysis"
   },
   "outputs": [],
   "source": [
    "# Example 3: Comparison of different student profiles\n",
    "print(\"\\n⚖️ Comparing Different Student Profiles\")\n",
    "print(\"=\" * 50)\n",
    "\n",
    "# Define different student profiles\n",
    "profiles = {\n",
    "    \"High Performer\": \"Excellent student with outstanding grades in all subjects. \\\n",
    "    Highly motivated, participates actively, and shows strong leadership skills.\",\n",
    "    \n",
    "    \"Average Student\": \"Decent performance with average grades. \\\n",
    "    Completes most assignments but sometimes lacks motivation. \\\n",
    "    Participates occasionally in class discussions.\",\n",
    "    \n",
    "    \"Struggling Student\": \"Has difficulty with most subjects and often misses deadlines. \\\n",
    "    Needs additional support and guidance. Shows some potential but lacks confidence.\"\n",
    "}\n",
    "\n",
    "# Analyze each profile\n",
    "profile_results = {}\n",
    "\n",
    "for profile_name, profile_text in profiles.items():\n",
    "    print(f\"\\n📋 {profile_name}:\")\n",
    "    print(f\"Description: {profile_text}\")\n",
    "    \n",
    "    # Process text\n",
    "    cleaned = preprocessor.clean_text(profile_text)\n",
    "    embedding = sbert_model.encode([cleaned], normalize_embeddings=True)[0]\n",
    "    \n",
    "    profile_results[profile_name] = {\n",
    "        'embedding': embedding,\n",
    "        'cleaned_text': cleaned,\n",
    "        'original_text': profile_text\n",
    "    }\n",
    "    \n",
    "    print(f\"{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "title_cell"
   },
   "source": [
    "# Student Performance Analysis - Complete Pipeline\n",
    "\n",
    "This notebook contains a complete machine learning pipeline for student performance analysis including:\n",
    "- Exploratory Data Analysis (EDA)\n",
    "- Text preprocessing and embeddings\n",
    "- Feature fusion and data splitting\n",
    "- Regression modeling\n",
    "- Clustering analysis\n",
    "- Interactive predictions\n",
    "\n",
    "**Instructions for Google Colab:**\n",
    "1. Upload your `StudentPerformanceFactors.csv` file to the Colab environment\n",
    "2. Run all cells in order\n",
    "3. The notebook will create output directories and save results automatically"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "setup_cell"
   },
   "source": [
    "## 🔧 Setup and Installation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "install_dependencies"
   },
   "outputs": [],
   "source": [
    "# Install required packages\n",
    "!pip install sentence-transformers nltk scikit-learn plotly seaborn tqdm joblib\n",
    "\n",
    "# Import all required libraries\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import plotly.express as px\n",
    "import plotly.graph_objects as go\n",
    "import os\n",
    "import json\n",
    "import joblib\n",
    "import re\n",
    "from time import time\n",
    "from pathlib import Path\n",
    "from typing import List, Tuple, Dict, Any, Set\n",
    "from collections import Counter\n",
    "from tqdm import tqdm\n",
    "\n",
    "# NLTK imports and downloads\n",
    "import nltk\n",
    "from nltk.tokenize import word_tokenize\n",
    "from nltk.corpus import stopwords\n",
    "from nltk.stem import WordNetLemmatizer\n",
    "\n",
    "# Download NLTK data\n",
    "nltk.download('punkt', quiet=True)\n",
    "nltk.download('stopwords', quiet=True)\n",
    "nltk.download('wordnet', quiet=True)\n",
    "nltk.download('averaged_perceptron_tagger', quiet=True)\n",
    "nltk.download('omw-1.4', quiet=True)\n",
    "\n",
    "# Sentence Transformers\n",
    "from sentence_transformers import SentenceTransformer\n",
    "\n",
    "# Sklearn imports\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import StandardScaler, OneHotEncoder\n",
    "from sklearn.impute import SimpleImputer\n",
    "from sklearn.compose import ColumnTransformer\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score\n",
    "from sklearn.linear_model import LinearRegression\n",
    "from sklearn.tree import DecisionTreeRegressor\n",
    "from sklearn.ensemble import RandomForestRegressor\n",
    "from sklearn.cluster import KMeans, AgglomerativeClustering\n",
    "from sklearn.metrics import silhouette_score\n",
    "\n",
    "# Set plot style\n",
    "sns.set(style='whitegrid')\n",
    "plt.rcParams['figure.figsize'] = (12, 6)\n",
    "\n",
    "# Constants\n",
    "RANDOM_STATE = 42\n",
    "TEST_SIZE = 0.2\n",
    "MODEL_NAME = 'all-MiniLM-L6-v2'\n",
    "BATCH_SIZE = 32\n",
    "\n",
    "print(\"✅ Setup completed successfully!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "file_upload_cell"
   },
   "source": [
    "## 📁 File Upload\n",
    "\n",
    "Upload your `StudentPerformanceFactors.csv` file here:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "upload_file"
   },
   "outputs": [],
   "source": [
    "from google.colab import files\n",
    "import io\n",
    "\n",
    "# Upload the dataset\n",
    "print(\"Please upload your StudentPerformanceFactors.csv file:\")\n",
    "uploaded = files.upload()\n",
    "\n",
    "# Check if file was uploaded\n",
    "if 'StudentPerformanceFactors.csv' in uploaded:\n",
    "    print(\"✅ File uploaded successfully!\")\n",
    "    # Create output directories\n",
    "    os.makedirs('output/eda_plots', exist_ok=True)\n",
    "    os.makedirs('output/embeddings', exist_ok=True)\n",
    "    os.makedirs('output/features', exist_ok=True)\n",
    "    os.makedirs('output/models', exist_ok=True)\n",
    "    os.makedirs('output/clustering', exist_ok=True)\n",
    "    print(\"📁 Output directories created.\")\n",
    "else:\n",
    "    print(\"❌ Please upload the StudentPerformanceFactors.csv file to continue.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "eda_section"
   },
   "source": [
    "## 📊 Step 1: Exploratory Data Analysis (EDA)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "eda_functions"
   },
   "outputs": [],
   "source": [
    "def detect_target_column(df):\n",
    "    \"\"\"Detect and return the target column name.\"\"\"\n",
    "    target_candidates = [col for col in df.columns if 'final' in col.lower() or 'score' in col.lower() or 'exam_score' in col.lower()]\n",
    "    if target_candidates:\n",
    "        return target_candidates[0]\n",
    "    return None\n",
    "\n",
    "def basic_data_analysis(df):\n",
    "    \"\"\"Perform basic data analysis and return summary.\"\"\"\n",
    "    info = {\n",
    "        'shape': df.shape,\n",
    "        'columns': list(df.columns),\n",
    "        'dtypes': df.dtypes.astype(str).to_dict(),\n",
    "        'missing_percentage': (df.isnull().mean() * 100).round(2).to_dict(),\n",
    "        'numeric_columns': df.select_dtypes(include=['int64', 'float64']).columns.tolist(),\n",
    "        'categorical_columns': df.select_dtypes(include=['object', 'category']).columns.tolist()\n",
    "    }\n",
    "    \n",
    "    target_col = detect_target_column(df)\n",
    "    if target_col:\n",
    "        info['target_column'] = target_col\n",
    "        if target_col in info['numeric_columns']:\n",
    "            correlations = df[info['numeric_columns']].corr()[target_col].sort_values(ascending=False)\n",
    "            info['correlations_with_target'] = correlations.to_dict()\n",
    "    \n",
    "    return info\n",
    "\n",
    "def plot_distributions(df, numeric_cols, output_dir):\n",
    "    \"\"\"Plot distributions for numeric columns.\"\"\"\n",
    "    for col in numeric_cols:\n",
    "        plt.figure(figsize=(10, 4))\n",
    "        sns.histplot(data=df, x=col, kde=True)\n",
    "        plt.title(f'Distribution of {col}')\n",
    "        plt.tight_layout()\n",
    "        plt.savefig(f'{output_dir}/dist_{col}.png')\n",
    "        plt.show()\n",
    "        plt.close()\n",
    "\n",
    "def plot_categorical_counts(df, categorical_cols, output_dir, max_categories=10):\n",
    "    \"\"\"Plot value counts for categorical columns.\"\"\"\n",
    "    for col in categorical_cols:\n",
    "        value_counts = df[col].value_counts()\n",
    "        if len(value_counts) > max_categories:\n",
    "            print(f\"Skipping {col} - too many categories ({len(value_counts)} > {max_categories})\")\n",
    "            continue\n",
    "            \n",
    "        plt.figure(figsize=(10, 4))\n",
    "        sns.countplot(data=df, x=col, order=value_counts.index)\n",
    "        plt.title(f'Count of {col}')\n",
    "        plt.xticks(rotation=45, ha='right')\n",
    "        plt.tight_layout()\n",
    "        plt.savefig(f'{output_dir}/count_{col}.png')\n",
    "        plt.show()\n",
    "        plt.close()\n",
    "\n",
    "def plot_correlation_heatmap(df, numeric_cols, output_dir):\n",
    "    \"\"\"Plot correlation heatmap for numeric columns.\"\"\"\n",
    "    if len(numeric_cols) < 2:\n",
    "        print(\"Not enough numeric columns for correlation heatmap.\")\n",
    "        return\n",
    "        \n",
    "    plt.figure(figsize=(12, 10))\n",
    "    corr = df[numeric_cols].corr()\n",
    "    mask = np.triu(np.ones_like(corr, dtype=bool))\n",
    "    sns.heatmap(corr, mask=mask, annot=True, fmt=\".2f\", cmap='coolwarm', \n",
    "                square=True, linewidths=0.5, cbar_kws={\"shrink\": .8})\n",
    "    plt.title('Correlation Heatmap')\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(f'{output_dir}/correlation_heatmap.png')\n",
    "    plt.show()\n",
    "    plt.close()\n",
    "\n",
    "print(\"✅ EDA functions defined successfully!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "run_eda"
   },
   "outputs": [],
   "source": [
    "# Load and analyze data\n",
    "print(\"📊 Starting Exploratory Data Analysis...\")\n",
    "\n",
    "# Load data\n",
    "df = pd.read_csv('StudentPerformanceFactors.csv')\n",
    "print(f\"Dataset loaded: {df.shape[0]} rows, {df.shape[1]} columns\")\n",
    "\n",
    "# Display basic info\n",
    "print(\"\\n📋 Dataset Info:\")\n",
    "print(df.info())\n",
    "\n",
    "print(\"\\n📋 First 5 rows:\")\n",
    "display(df.head())\n",
    "\n",
    "# Perform basic analysis\n",
    "analysis = basic_data_analysis(df)\n",
    "\n",
    "# Save analysis summary\n",
    "with open('output/eda_summary.json', 'w') as f:\n",
    "    json.dump(analysis, f, indent=2)\n",
    "\n",
    "# Print summary\n",
    "print(f\"\\n📈 Analysis Summary:\")\n",
    "print(f\"- Total rows: {analysis['shape'][0]}, columns: {analysis['shape'][1]}\")\n",
    "print(f\"- Numeric columns: {len(analysis['numeric_columns'])}\")\n",
    "print(f\"- Categorical columns: {len(analysis['categorical_columns'])}\")\n",
    "print(f\"- Target column: {analysis.get('target_column', 'Not detected')}\")\n",
    "\n",
    "# Check for missing values\n",
    "missing_cols = {k: v for k, v in analysis['missing_percentage'].items() if v > 0}\n",
    "if missing_cols:\n",
    "    print(\"\\n⚠️ Columns with missing values:\")\n",
    "    for col, pct in missing_cols.items():\n",
    "        print(f\"- {col}: {pct}% missing\")\n",
    "else:\n",
    "    print(\"\\n✅ No missing values found.\")\n",
    "\n",
    "# Create visualizations\n",
    "print(\"\\n📊 Creating visualizations...\")\n",
    "plot_distributions(df, analysis['numeric_columns'], 'output/eda_plots')\n",
    "plot_categorical_counts(df, analysis['categorical_columns'], 'output/eda_plots')\n",
    "\n",
    "if len(analysis['numeric_columns']) > 1:\n",
    "    plot_correlation_heatmap(df, analysis['numeric_columns'], 'output/eda_plots')\n",
    "\n",
    "print(\"✅ EDA completed successfully!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "text_processing_section"
   },
   "source": [
    "## 🔤 Step 2: Text Preprocessing and Embeddings"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "text_processing_functions"
   },
   "outputs": [],
   "source": [
    "def get_stop_words() -> Set[str]:\n",
    "    \"\"\"Get English stop words from NLTK with additional common words.\"\"\"\n",
    "    try:\n",
    "        stop_words = set(stopwords.words('english'))\n",
    "        additional_stopwords = {\n",
    "            'also', 'could', 'would', 'should', 'might', 'must', 'shall',\n",
    "            'may', 'need', 'use', 'like', 'get', 'go', 'one', 'two', 'three',\n",
    "            'first', 'second', 'third', 'many', 'much', 'well', 'even', 'still',\n",
    "            'without', 'since', 'though', 'whether', 'another', 'however',\n",
    "            'therefore', 'thus', 'hence', 'meanwhile', 'furthermore', 'moreover',\n",
    "            'nevertheless', 'nonetheless', 'accordingly', 'consequently',\n",
    "            'otherwise', 'similarly', 'thereby', 'whereas', 'yet', 'thus'\n",
    "        }\n",
    "        return stop_words.union(additional_stopwords)\n",
    "    except Exception as e:\n",
    "        print(f\"Warning: Could not load stop words: {e}\")\n",
    "        return set()\n",
    "\n",
    "class TextPreprocessor:\n",
    "    \"\"\"Handles text preprocessing including cleaning, tokenization, and lemmatization.\"\"\"\n",
    "    \n",
    "    def __init__(self, stop_words: Set[str] = None):\n",
    "        self.stop_words = stop_words or get_stop_words()\n",
    "        self.lemmatizer = WordNetLemmatizer()\n",
    "    \n",
    "    def clean_text(self, text: str, verbose: bool = False) -> str:\n",
    "        \"\"\"Clean and preprocess a single text string.\"\"\"\n",
    "        if not isinstance(text, str):\n",
    "            return \"\"\n",
    "            \n",
    "        if verbose:\n",
    "            print(f\"\\nOriginal: {text}\")\n",
    "        \n",
    "        # Convert to lowercase\n",
    "        text_lower = text.lower()\n",
    "        \n",
    "        # Remove special characters and numbers\n",
    "        text_clean = re.sub(r'[^a-zA-Z\\s]', ' ', text_lower)\n",
    "        \n",
    "        # Tokenization\n",
    "        tokens = word_tokenize(text_clean)\n",
    "        \n",
    "        # Remove stopwords and short tokens\n",
    "        filtered_tokens = [token for token in tokens \n",
    "                         if token not in self.stop_words and len(token) > 1]\n",
    "        \n",
    "        # Lemmatization\n",
    "        lemmatized_tokens = [self.lemmatizer.lemmatize(token) for token in filtered_tokens]\n",
    "        \n",
    "        processed_text = ' '.join(lemmatized_tokens)\n",
    "        \n",
    "        if verbose:\n",
    "            print(f\"Processed: {processed_text}\")\n",
    "        \n",
    "        return processed_text\n",
    "\n",
    "def detect_text_column(df: pd.DataFrame) -> str:\n",
    "    \"\"\"Detect the most likely text column in the dataframe.\"\"\"\n",
    "    text_columns = []\n",
    "    text_like_columns = []\n",
    "    \n",
    "    for col in df.columns:\n",
    "        if df[col].dtype == 'object' and df[col].str.contains('[a-zA-Z]').any():\n",
    "            text_columns.append(col)\n",
    "            if any(keyword in col.lower() for keyword in ['text', 'profile', 'note', 'description', 'comment']):\n",
    "                text_like_columns.append(col)\n",
    "    \n",
    "    if text_like_columns:\n",
    "        return text_like_columns[0]\n",
    "    elif text_columns:\n",
    "        return text_columns[0]\n",
    "    else:\n",
    "        string_cols = [col for col in df.columns if df[col].dtype == 'object']\n",
    "        if string_cols:\n",
    "            df['combined_text'] = df[string_cols].astype(str).agg(' '.join, axis=1)\n",
    "            return 'combined_text'\n",
    "        else:\n",
    "            raise ValueError(\"No suitable text column found in the dataset.\")\n",
    "\n",
    "def save_embeddings_stats(embeddings: np.ndarray, output_file: str) -> None:\n",
    "    \"\"\"Save basic statistics about the embeddings.\"\"\"\n",
    "    stats = {\n",
    "        'num_embeddings': embeddings.shape[0],\n",
    "        'embedding_dimension': embeddings.shape[1],\n",
    "        'mean_norm': float(np.mean(np.linalg.norm(embeddings, axis=1))),\n",
    "        'min_norm': float(np.min(np.linalg.norm(embeddings, axis=1))),\n",
    "        'max_norm': float(np.max(np.linalg.norm(embeddings, axis=1))),\n",
    "        'mean_values': [float(x) for x in np.mean(embeddings, axis=0)[:5]],\n",
    "        'std_values': [float(x) for x in np.std(embeddings, axis=0)[:5]]\n",
    "    }\n",
    "    \n",
    "    with open(output_file, 'w') as f:\n",
    "        json.dump(stats, f, indent=2)\n",
    "\n",
    "print(\"✅ Text preprocessing functions defined successfully!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "run_text_processing"
   },
   "outputs": [],
   "source": [
    "# Run text preprocessing\n",
    "print(\"🔤 Starting text preprocessing...\")\n",
    "\n",
    "# Detect text column\n",
    "text_column = detect_text_column(df)\n",
    "print(f\"Detected text column: '{text_column}'\")\n",
    "print(f\"Sample text: {df[text_column].iloc[0][:100]}...\")\n",
    "\n",
    "# Initialize preprocessor\n",
    "preprocessor = TextPreprocessor()\n",
    "print(f\"Using {len(preprocessor.stop_words)} stop words\")\n",
    "\n",
    "# Show example processing\n",
    "print(\"\\n🔍 Example text processing:\")\n",
    "sample_text = df[text_column].dropna().iloc[0]\n",
    "_ = preprocessor.clean_text(sample_text, verbose=True)\n",
    "\n",
    "# Process all text\n",
    "print(\"\\n⚙️ Processing all texts...\")\n",
    "tqdm.pandas(desc=\"Cleaning text\")\n",
    "df['cleaned_text'] = df[text_column].progress_apply(preprocessor.clean_text)\n",
    "\n",
    "# Save cleaned text\n",
    "text_df = df[[text_column, 'cleaned_text']].copy()\n",
    "text_df.columns = ['original_profile_text', 'cleaned_profile_text']\n",
    "text_df.to_csv('output/embeddings/text_data.csv', index=False)\n",
    "\n",
    "# Generate embeddings\n",
    "print(\"\\n🧠 Generating SBERT embeddings...\")\n",
    "model = SentenceTransformer(MODEL_NAME)\n",
    "texts = df['cleaned_text'].tolist()\n",
    "\n",
    "# Process in batches\n",
    "embeddings = []\n",
    "for i in tqdm(range(0, len(texts), BATCH_SIZE), desc=\"Generating embeddings\"):\n",
    "    batch = texts[i:i + BATCH_SIZE]\n",
    "    batch_embeddings = model.encode(\n",
    "        batch,\n",
    "        batch_size=BATCH_SIZE,\n",
    "        show_progress_bar=False,\n",
    "        convert_to_numpy=True,\n",
    "        normalize_embeddings=True\n",
    "    )\n",
    "    embeddings.append(batch_embeddings)\n",
    "\n",
    "# Combine all batches\n",
    "embeddings = np.vstack(embeddings)\n",
    "\n",
    "# Save embeddings and stats\n",
    "np.save('output/embeddings/embeddings.npy', embeddings)\n",
    "save_embeddings_stats(embeddings, 'output/embeddings/embeddings_stats.json')\n",
    "\n",
    "print(f\"\\n✅ Text processing completed!\")\n",
    "print(f\"- Processed {len(df)} documents\")\n",
    "print(f\"- Embedding dimension: {embeddings.shape[1]}\")\n",
    "print(f\"- Total embeddings size: {embeddings.nbytes / (1024*1024):.2f} MB\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "feature_fusion_section"
   },
   "source": [
    "## 🔗 Step 3: Feature Fusion and Data Splitting"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "feature_fusion_functions"
   },
   "outputs": [],
   "source": [
    "def get_feature_columns(df, target_col):\n",
    "    \"\"\"Identify numeric and categorical feature columns.\"\"\"\n",
    "    exclude_cols = [target_col, 'combined_text', 'cleaned_text'] + [\n",
    "        col for col in df.columns \n",
    "        if col.lower().endswith(('text', 'description', 'notes', 'name', 'id'))\n",
    "    ]\n",
    "    \n",
    "    numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()\n",
    "    numeric_cols = [col for col in numeric_cols if col not in exclude_cols]\n",
    "    \n",
    "    categorical_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()\n",
    "    categorical_cols = [col for col in categorical_cols if col not in exclude_cols]\n",
    "    \n",
    "    return numeric_cols, categorical_cols\n",
    "\n",
    "def create_preprocessor(numeric_cols, categorical_cols):\n",
    "    \"\"\"Create a column transformer for preprocessing.\"\"\"\n",
    "    numeric_transformer = Pipeline(steps=[\n",
    "        ('imputer', SimpleImputer(strategy='median')),\n",
    "        ('scaler', StandardScaler())\n",
    "    ])\n",
    "    \n",
    "    categorical_transformer = Pipeline(steps=[\n",
    "        ('imputer', SimpleImputer(strategy='most_frequent')),\n",
    "        ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))\n",
    "    ])\n",
    "    \n",
    "    preprocessor = ColumnTransformer(\n",
    "        transformers=[\n",
    "            ('num', numeric_transformer, numeric_cols),\n",
    "            ('cat', categorical_transformer, categorical_cols)\n",
    "        ],\n",
    "        remainder='drop'\n",
    "    )\n",
    "    \n",
    "    return preprocessor\n",
    "\n",
    "def save_feature_names(preprocessor, numeric_cols, categorical_cols, output_dir):\n",
    "    \"\"\"Save feature names after one-hot encoding.\"\"\"\n",
    "    feature_names = numeric_cols.copy()\n",
    "    \n",
    "    if categorical_cols:\n",
    "        try:\n",
    "            ohe = preprocessor.named_transformers_['cat'].named_steps['onehot']\n",
    "            if hasattr(ohe, 'categories_'):\n",
    "                for i, col in enumerate(categorical_cols):\n",
    "                    if i < len(ohe.categories_):\n",
    "                        unique_vals = ohe.categories_[i][:10]\n",
    "                        for val in unique_vals:\n",
    "                            feature_names.append(f\"{col}_{val}\")\n",
    "            else:\n",
    "                for col in categorical_cols:\n",
    "                    feature_names.append(f\"{col}_category\")\n",
    "        except Exception as e:\n",
    "            print(f\"Warning: Could not generate categorical feature names: {str(e)}\")\n",
    "            for col in categorical_cols:\n",
    "                feature_names.append(f\"{col}_category\")\n",
    "    \n",
    "    # Add embedding dimensions\n",
    "    embedding_dims = 384  # all-MiniLM-L6-v2 has 384 dimensions\n",
    "    feature_names.extend([f\"sbert_{i}\" for i in range(embedding_dims)])\n",
    "    \n",
    "    os.makedirs(output_dir, exist_ok=True)\n",
    "    output_file = os.path.join(output_dir, \"feature_names.txt\")\n",
    "    \n",
    "    try:\n",
    "        with open(output_file, 'w', encoding='utf-8') as f:\n",
    "            for name in feature_names:\n",
    "                f.write(f\"{name}\\n\")\n",
    "        print(f\"Saved feature names to {output_file}\")\n",
    "        return feature_names\n",
    "    except Exception as e:\n",
    "        print(f\"Warning: Could not save feature names: {str(e)}\")\n",
    "        return []\n",
    "\n",
    "print(\"✅ Feature fusion functions defined successfully!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "run_feature_fusion"
   },
   "outputs": [],
   "source": [
    "# Run feature fusion\n",
    "print(\"🔗 Starting feature fusion...\")\n",
    "\n",
    "# Detect target column\n",
    "target_col = detect_target_column(df)\n",
    "